main: me.elexation.exxentials.Exxentials
name: Exxentials
version: 1.0
author: Elexation
api-version: 1.16

permissions:
  exxentials.*:
    description: All perms
    default: op
  exxentials.track:
    default: true
  exxentials.delwarp:
    default: op
  exxentials.setspawn:
    default: op
  exxentials.spawn:
    default: true
  exxentials.butcher:
    default: op
  exxentials.afk:
    default: true
  exxentials.heal:
    default: op
  exxentials.gamemode:
    default: op
  exxentials.nickname:
    default: op
  exxentials.vanish:
    default: op
  exxentials.fly:
    default: op
  exxentials.color:
    default: op
  exxentials.warp:
    default: true
  exxentials.setwarp:
    default: op
  exxentials.msg:
    default: true
  exxentials.god:
    default: op
  exxentials.reload:
    default: op
  exxentials.sudo:
    default: op

commands:
  Sudo:
    description: Force a player to perform a command
  Exreload:
    aliases:
      - exrl
    description: Reloads Exxentials
  God:
    description: God mode
  Trackstop:
    description: Stop tracking
  Track:
    description: Track a player while holding a compass
  Delwarp:
    description: Deletes an existing warp
  Warp:
    description: Teleport to a warp
  Setwarp:
    description: Sets a new warp
  Setspawn:
    description: Sets spawn
  Spawn:
    description: Sends you to spawn
  Reply:
    aliases:
      - r
    description: Reply to a player's message
  Msg:
    aliases:
      - w
      - whisper
      - tell
    decription: Message a player privately
  Butcher:
    aliases:
    description: Kills all hostile mobs
  Nickname:
    aliases:
      - nick
    description: Changes specified player nickname
  Gms:
    aliases:
    description: Sets specified player to gamemode survival
  Gmc:
    aliases:
    description: Sets specified player to gamemode creative
  Gamemode:
    aliases:
      - gm
    description: Changes gamemode of specified player
  Heal:
    aliases:
    description: Will heal a specified player
  Vanish:
    aliases:
      - v
    description: Puts you in vanish mode
  Afk:
    aliases:
    description: afk
  Fly:
    aliases:
    description: Enable or disable fly
